---
version: '3'

services:
    traefik:
        image: traefik:v2.0
        restart: always
        command:
            - "--api.insecure=true"
            - "--entrypoints.web.address=:80"
            - "--providers.docker"
            - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    adapter:
        build: ./adapter
        network_mode: host
        env_file: ./.adapter.env.local
        restart: always
    grouper:
        build: ./grouper
        env_file: ./.grouper.env.local
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grouper.rule=PathPrefix(`/api/v1/grouper/`)"
            - "traefik.http.routers.grouper.entrypoints=web"
    directory:
        build: ./directory
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.directory.rule=PathPrefix(`/api/v1/directory/`)"
            - "traefik.http.routers.directory.entrypoints=web"
    client:
        build: ./client
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.client.rule=PathPrefix(`/`)"
            - "traefik.http.routers.client.entrypoints=web"
